version: '2'
services:
  code-server:
    container_name: ${CONTAINER_NAME:-code-server}
    image: codercom/code-server:latest
    restart: unless-stopped
    ports:
      - ${HTTP_PORT:-8080}:8080
    volumes:
      - ${CONFIG_PATH:-/home/kyle/docker/code-server/config}:/home/coder/.config
