version: '2'
services:
  code-server:
    container_name: code-server
    image: codercom/code-server:latest
    restart: unless-stopped
    ports:
      - ${HTTP_PORT:-8080}:8080
    environment:
      - DOCKER_USER=kyle