version: '2'
services:
  code-server:
    container_name: ${CONTAINER_NAME:-code-server}
    image: codercom/code-server:latest
    restart: unless-stopped
    ports:
      - ${HTTP_PORT:-8080}:8080
    volumes:
      - configvolume:/home/coder/.config
volumes:
  configvolume:
    external:
      name: ${CONTAINER_NAME:-code-server}-config-volume
